source.. = src/,\
           xtend-gen/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               libs/json-20171018.jar
bin.excludes = **/*.xtend
src.includes = icons/
jars.compile.order = .,\
                     libs/json-20171018.jar
source.libs/json-20171018.jar = C:\RoboTool_new\tradutor-plugin\robosim-b-ufrn-gen
